apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager # the NS you're running cert-manager in
  name: zerossl-eab
stringData:
  secret: TILT_PLACEHOLDER:eab_hmacKey
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: TILT_PLACEHOLDER:eab_kid
      keySecretRef:
        name: zerossl-eab
        key: secret
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-key-prod5
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: gateway-http
              #namespace: traefik
              kind: Gateway
            - name: gateway-https
              #namespace: traefik
              kind: Gateway