apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager # the NS you're running cert-manager in
  name: zero-sll-eabsecret
stringData:
  secret: TILT_PLACEHOLDER:eab_hmacKey
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: TILT_PLACEHOLDER:eab_kid
      keySecretRef:
        name: zero-sll-eabsecret
        key: secret
      keyAlgorithm: HS256
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: traefik
              namespace: traefik
              kind: Gateway