apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: main
build:
  artifacts:
  - image: dm-server
    context: .
    docker:
      dockerfile: Packages/server/Dockerfile
    sync:
      manual:
        - src: 'Packages/server/**/*'
          dest: '/dm_server'
        # don't worry, this only actually syncs the specific subpaths listed in .dockerignore (source: NodeModuleWatchPaths.js)
        - src: 'node_modules/**/*'
          dest: '/dm_server'
    # sync:
    #   infer:
    #     - 'Packages/server/**/*'
    #     # don't worry, this only actually syncs the specific subpaths listed in .dockerignore (source: NodeModuleWatchPaths.js)
    #     - 'node_modules/**/*'
deploy:
  kubectl:
    manifests:
    - packages\server\deployment.yaml