apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: main
build:
  artifacts:
  - image: packages-server
    sync:
      manual:
        # sync server's transpiled code (we don't want image re-deploy just from these changes)
        #- src: 'Packages/server/Dist/**/*.*'
        #  strip: 'Packages/server/Dist'
        #  dest: 'Dist' # relative to "/dm_server/Packages/server"

        # test; have sync try to sync all folders/files
        #- src: '**/*.*'
        - src: 'Packages/server/**/*.*'
          strip: 'Packages/server'
          dest: '/dm_server/Packages/server'

# custom replaced
#    context: Packages/server
#    docker:
#      dockerfile: Dockerfile
    context: .
    docker:
      dockerfile: Packages/server/Dockerfile


deploy:
  kubectl:
    manifests:
    - packages\server\deployment.yaml