apiVersion: v1
kind: Secret
metadata:
 name: debate-map-pguser-admin
 #namespace: app
 namespace: default
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "postgres-operator/debate-map-pguser-admin"