apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
        - image: google/cadvisor
          name: cadvisor
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/run
              name: cadvisor-claim0
            - mountPath: /sys
              name: cadvisor-claim1
              readOnly: true
            - mountPath: /var/lib/docker
              name: cadvisor-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: cadvisor-claim0
          persistentVolumeClaim:
            claimName: cadvisor-claim0
        - name: cadvisor-claim1
          persistentVolumeClaim:
            claimName: cadvisor-claim1
            readOnly: true
        - name: cadvisor-claim2
          persistentVolumeClaim:
            claimName: cadvisor-claim2
            readOnly: true
status: {}
