apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:

  # v-added
  type: NodePort

  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080

      # v-added
      nodePort: 31001

  selector:
    io.kompose.service: cadvisor
status:
  loadBalancer: {}
