apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  
  # v-added
  type: NodePort

  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000

      # v-added
      nodePort: 31000
      
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
