apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: node-exporter
    spec:
      containers:
        - args:

            # v-replaced
            - --path.procfs=/proc
            - --path.sysfs=/sys
            #- --collector.systemd.private
            #- --collector.filesystem.ignored-mount-points
            #- ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($|/)

          image: prom/node-exporter
          name: node-exporter
          ports:
            - containerPort: 9100
          resources: {}

          # v-removed
          # volumeMounts:
          #   - mountPath: /host/proc
          #     name: node-exporter-claim0
          #     readOnly: true
          #   - mountPath: /host/sys
          #     name: node-exporter-claim1
          #     readOnly: true
      
      restartPolicy: Always
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
            readOnly: true
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
            readOnly: true
status: {}
