apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Root\Apps\Global\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:

  # v-replaced
  # ports:
  #   - name: "9090"
  #     port: 9090
  #     targetPort: 9090
  clusterIP: None

  selector:
    io.kompose.service: prometheus
status:
  loadBalancer: {}
