# for regular (debian:buster-slim) builds (from: https://github.com/rui314/mold#how-to-use)
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

# for musl-based linux builds (eg. when trying to deploy to an alpine image)
[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold", "-C", "link-args=-z text"] # suggested on discord
# from: https://stackoverflow.com/a/70378019
# this variant doesn't work fsr; get error: "= note: clang: error: unsupported option '--ld-path=/usr/local/bin/mold'"
#rustflags = ["-C", "link-arg=--ld-path=/usr/local/bin/mold"]

# for windows
[target.x86_64-pc-windows-msvc]
# using lld as a linker is apparently faster and better written than the current default (and is set to soon become the new default)
linker = "rust-lld.exe"