[package]
name = "app-server-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
async-trait = "0.1.52"
url = "2"
#crossbeam-channel = "0.5.2"
flume = "0.10.10"
async-broadcast = "0.4.0"
hyper = {version = "0.14.16", features = ["client"] }
deadpool = {version = "0.9.2", features = ["rt_tokio_1"]}
deadpool-postgres = "0.10.1"
indexmap = "1.8.0"
#dashmap = "4.0.2" # the API is hard to use correctly/safely (there are rules you have to follow that aren't compiled-ensured)
flurry = "0.4.0"
async-recursion = "1.0.0"
#refinery = { version = "0.8.4", features = ["tokio-postgres"]}
metrics = "0.18.1"
log = "0.4.16"
regex = "1.5.5"
itertools = "0.10.3"
lazy_static = "1.4.0"
num_cpus = "1.0"
jsonschema = "0.16"
base64 = "0.13.0"
#tokio-pg-mapper = "0.2.0"
#tokio-pg-mapper-derive = "0.2.0"
dyn-clone = "1.0.4"
once_cell = "1.13.0"

# needed for async-graphql examples-base, for now
slab = "0.4.2"
futures-util = "0.3.0"
futures-timer = "3.0.2"

#rust-macros = { path = "../rust-macros" }
rust-shared = { path = "../rust-shared" }

# sync among all rust crates (ie. deps that have issues being subdeps accessed through rust_shared)
# ==========

serde = "1.0.144"