[package]
name = "app-server-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
axum = { version = "0.4.3", features = ["ws"] }
async-graphql = "3.0.22"
async-graphql-axum = "3.0.22"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
#tower-web = "0.3.7"
tower-http = { version = "0.2.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
anyhow = "1.0"
async-trait = "0.1.52"
uuid = { version = "0.8", features = ["serde", "v4"] }
#crossbeam-channel = "0.5.2"
flume = "0.10.10"

# needed for async-graphql "scalar!" macro
serde = "*"
serde_json = "1.0.76"
# needed for tokio-postgres
bytes = "1.0"

# needed for async-graphql examples-base, for now
slab = "0.4.2"
futures-util = "0.3.0"
futures-timer = "3.0.2"

# needed for async-graphql-axum customization
tower-service = "0.3"

[dependencies.tokio-postgres]
git = "https://github.com/petrosagg/rust-postgres.git"
branch = "copy-both"
features = [ "with-serde_json-1" ] # needed for serde_json::Value to auto-convert to a declared struct