[package]
name = "app-server-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
axum = { version = "0.4.3", features = ["ws"] }
async-graphql = "3.0.22"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
#tower-web = "0.3.7"
tower-http = { version = "0.2.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
# needed for tokio-postgres
bytes = "1.0"

[dependencies.tokio-postgres]
git = "https://github.com/petrosagg/rust-postgres.git"
branch = "copy-both"