[package]
name = "app-server-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
#axum = { version = "0.4.5", features = ["ws"] }
axum = { git = "https://github.com/tokio-rs/axum.git", rev = "15914c4f15b375d5785b7f95be7685abba326c5e", features = ["ws", "headers", "json"] }
async-graphql = "3.0.28"
async-graphql-axum = "3.0.28"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
#tower-web = "0.3.7"
tower-http = { version = "0.2.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
anyhow = "1.0"
async-trait = "0.1.52"
url = "2"
uuid = { version = "0.8", features = ["serde", "v4"] }
#crossbeam-channel = "0.5.2"
flume = "0.10.10"
async-broadcast = "0.4.0"
hyper = {version = "0.14.16", features = ["client"] }
deadpool = {version = "0.9.2", features = ["rt_tokio_1"]}
deadpool-postgres = "0.10.1"
indexmap = "1.8.0"
#dashmap = "4.0.2" # the API is hard to use correctly/safely (there are rules you have to follow that aren't compiled-ensured)
flurry = "0.4.0"
async-recursion = "1.0.0"
#refinery = { version = "0.8.4", features = ["tokio-postgres"]}
metrics = "0.18.1"
log = "0.4.16"
regex = "1.5.5"
itertools = "0.10.3"
lazy_static = "1.4.0"
num_cpus = "1.0"
jsonschema = "0.16"

# needed for async-graphql "scalar!" macro
serde = "*"
serde_json = "1.0.76"
# needed for tokio-postgres
bytes = "1.0"

# needed for async-graphql examples-base, for now
slab = "0.4.2"
futures-util = "0.3.0"
futures-timer = "3.0.2"

# needed for async-graphql-axum customization
tower-service = "0.3"

rust-macros = { path = "../rust-macros" }
rust-shared = { path = "../rust-shared" }

[dependencies.tokio-postgres]
git = "https://github.com/petrosagg/rust-postgres.git"
branch = "copy-both"
features = [
	"with-serde_json-1", # needed for serde_json::Value to auto-convert to a declared struct
	"array-impls"
]