apiVersion: v1
kind: Service
metadata:
  name: dm-app-server-rs
  #namespace: app
  labels:
    app: dm-app-server-rs
spec:
  #clusterIP: None
  selector:
    app: dm-app-server-rs
  # to make it accessible outside of cluster
  #type: NodePort
  ports:
    - name: main
      port: 3105
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-app-server-rs
  #namespace: app
  labels:
    app: dm-app-server-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-app-server-rs
  template:
    metadata:
      labels:
        app: dm-app-server-rs
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
      - name: dm-app-server-rs
        image: "TILT_PLACEHOLDER:imageURL_appServerRS"
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3105
          initialDelaySeconds: 10999999 # mode: profiling
          #initialDelaySeconds: 20 # mode: normal
          periodSeconds: 10
          #timeoutSeconds: 3
          timeoutSeconds: 60 # temporarily increasing this to 60s; it seems the health-check responses have become too slow [~25s] sometimes! (not sure how; need to investigate)
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: password } }
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"