apiVersion: v1
kind: Service
metadata:
  name: dm-server
  namespace: dm-pg-operator
  labels:
    app: dm-server
spec:
  #clusterIP: None
  selector:
    app: dm-server
  # to make it accessible outside of cluster
  type: NodePort
  ports:
    - port: 3105
      targetPort: 3105
      nodePort: 31105
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-server
  namespace: dm-pg-operator
  labels:
    app: dm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-server
  template:
    metadata:
      labels:
        app: dm-server
    spec:
      containers:
      - name: dm-server
        image: dm-server
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3105
          initialDelaySeconds: 10999999
          periodSeconds: 5
          timeoutSeconds: 3
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: password } }
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"