apiVersion: v1
kind: Service
metadata:
  name: dm-server
  namespace: postgres-operator
  labels:
    app: dm-server
spec:
  clusterIP: None
  selector:
    app: dm-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-server
  namespace: postgres-operator
  labels:
    app: dm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-server
  template:
    metadata:
      labels:
        app: dm-server
    spec:
      containers:
      - name: dm-server
        image: dm-server
        #livenessProbe: TODO
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
        # - name: KEYCLOAK_USER
        #   value: "admin"
        # - name: KEYCLOAK_PASSWORD
        #   value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"