kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dmvx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    # commented; this was forcing all routes (including "web") to use tls, even though only the "websecure" route supports it (which was making non-https requests unresolvable, ie. always returning 404)
    # (note that with this commented, the websecure route now requires the tls:true flag, else it has the same issue in the opposite direction)
    #traefik.ingress.kubernetes.io/router.tls: "true"
    #traefik.ingress.kubernetes.io/router.tls.certresolver: default

    # ingress.kubernetes.io/hsts-max-age: "315360000"
    # ingress.kubernetes.io/hsts-include-subdomains: "true"
    # ingress.kubernetes.io/custom-frame-options-value: "SAMEORIGIN"
    # ingress.kubernetes.io/content-type-nosniff: "true"
    # ingress.kubernetes.io/browser-xss-filter: "true"
    #traefik.ingress.kubernetes.io/custom-response-headers: "Server:||X-Application-Context:||X-Powered-By:||exception:||Access-Control-Allow-Headers:CONNECT, DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT"
spec:
  rules:
    # these allow you to open the site directly, using the ovh cluster domain-name
    - host: 9m2x1z.nodes.c1.or1.k8s.ovh.us
      http:
        paths:
          - backend:
              serviceName: dm-web-server
              servicePort: 3005
    - host: app-server.9m2x1z.nodes.c1.or1.k8s.ovh.us
      http:
        paths:
          - backend:
              serviceName: dm-app-server-rs
              servicePort: 3105
    - host: app-server-js.9m2x1z.nodes.c1.or1.k8s.ovh.us
      http:
        paths:
          - backend:
              serviceName: dm-app-server-js
              servicePort: 3155
    # these are the domains end-users should be accessing the site from
    - host: debates.app
      http:
        # middlewares:
        #   test-stripprefix:
        #     stripPrefix:
        #       prefixes:
        #         - "/app-server"
        #         - "/app-server/"
        #   testHeader:
        #     headers:
        #       accessControlAllowMethods:
        #         - CONNECT
        #         - DELETE
        #         - GET
        #         - HEAD
        #         - OPTIONS
        #         - PATCH
        #         - POST
        #         - PUT
        paths:
          -
            # path: "/"
            # pathType: "Prefix"
            # priority: 1
            backend:
              #serviceName: dmvx-service
              serviceName: dm-web-server
              #servicePort: 8765
              #servicePort: 8080
              servicePort: 3005
          # - path: "/app-server/"
          #   pathType: "Prefix"
          #   priority: 2
          #   backend:
          #     serviceName: dm-app-server
          #     servicePort: 3105
    - host: app-server.debates.app
      http:
        paths:
          - backend:
              serviceName: dm-app-server-rs
              servicePort: 3105
    - host: app-server-js.debates.app
      http:
        paths:
          - backend:
              serviceName: dm-app-server-js
              servicePort: 3155