kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dmvx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: dm.venryx.org
      http:
        middlewares:
          test-stripprefix:
            stripPrefix:
              prefixes:
                - "/app-server"
        paths:
          - path: "/"
            backend:
              #serviceName: dmvx-service
              serviceName: dm-web-server
              #servicePort: 8765
              servicePort: 8080
          - path: "/app-server/"
            pathType: "Prefix"
            backend:
              serviceName: dm-app-server
              servicePort: 3105
    # - host: app-server.dm.venryx.org
    #   http:
    #     paths:
    #       - backend:
    #           serviceName: dm-app-server
    #           servicePort: 3105