kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dmvx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: dm.venryx.org
      http:
        paths:
          - backend:
              #serviceName: dmvx-service
              serviceName: dm-web-server
              #servicePort: 8765
              servicePort: 8080