apiVersion: v1
kind: Service
metadata:
  name: dm-monitor-backend
  #namespace: app
  labels:
    app: dm-monitor-backend
spec:
  #clusterIP: None
  selector:
    app: dm-monitor-backend
  # to make it accessible outside of cluster
  #type: NodePort
  ports:
    - name: main
      port: 5130
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-monitor-backend
  #namespace: app
  labels:
    app: dm-monitor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-monitor-backend
  template:
    metadata:
      labels:
        app: dm-monitor-backend
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
      - name: dm-monitor-backend
        image: "TILT_PLACEHOLDER:imageURL_monitorBackend"
        resources:
          limits:
            #cpu: "900m" # commented atm, due to limits apparently causing slowdown, even if limit not reached (see: https://erickhun.com/posts/kubernetes-faster-services-no-cpu-limits)
            memory: 1000Mi # if it ends up using more than this, it is likely a memory leak; kill and restart should restore regular performance
        livenessProbe:
          httpGet:
            path: /health-check
            port: 5130
          initialDelaySeconds: 10999999 # mode: profiling
          #initialDelaySeconds: 20 # mode: normal
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: password } }
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        # just reuse the db-password as the admin-key for now
        - name: MONITOR_BACKEND_ADMIN_KEY
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: password } }