apiVersion: v1
kind: Service
metadata:
  name: dm-app-server-js
  #namespace: app
  labels:
    app: dm-app-server-js
spec:
  #clusterIP: None
  selector:
    app: dm-app-server-js
  # to make it accessible outside of cluster
  #type: NodePort
  ports:
    - name: main
      port: 5115
      protocol: TCP
    # this port is for the NodeJS inspector
    - name: nodejs-inspector
      port: 5116
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-app-server-js
  #namespace: app
  labels:
    app: dm-app-server-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-app-server-js
  template:
    metadata:
      labels:
        app: dm-app-server-js
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
      - name: dm-app-server-js
        image: "TILT_PLACEHOLDER:imageURL_appServerJS"
        resources:
          requests:
            memory: 500Mi
          limits:
            #cpu: "900m" # commented atm, due to limits apparently causing slowdown, even if limit not reached (see: https://erickhun.com/posts/kubernetes-faster-services-no-cpu-limits)
            # if it ends up using more than this, it is likely a memory leak; kill and restart should restore regular performance
            memory: 3000Mi
        livenessProbe:
          httpGet:
            path: /health-check
            port: 5115
          #initialDelaySeconds: 10999999 # mode: profiling
          initialDelaySeconds: 20 # mode: normal
          periodSeconds: 10
          #timeoutSeconds: 3
          timeoutSeconds: 60 # temporarily increasing this to 60s; it seems the health-check responses have become too slow [~25s] sometimes! (not sure how; need to investigate)
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: debate-map-pguser-admin, key: password } }
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"