---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: my-gateway-class
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: my-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        certificateRefs:
          - kind: Secret
            name: zerossl-key-prod
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: my-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
  - "9m2x1z.nodes.c1.or1.k8s.ovh.us"
  - "debating.app"
  - "debates.app"
  rules:
    # - matches:
    #     - path:
    #         type: Exact
    #         value: /foo
    #   backendRefs:
    #     - name: whoami
    #       port: 80
    #       weight: 1
    - backendRefs:
      - name: dm-web-server
        port: 5100
      - name: dm-app-server-rs
        port: 5110
      - name: dm-app-server-js
        port: 5115
      - name: dm-monitor-backend
        port: 5130