# todo: get certificate provisioning working again
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: my-gateway-class
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: my-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        certificateRefs:
          - kind: Secret
            name: zerossl-key-prod
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-web-server
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
  - "9m2x1z.nodes.c1.or1.k8s.ovh.us"
  - "debating.app"
  - "debates.app"
  rules:
    # - matches:
    #     - path:
    #         type: Exact
    #         value: /foo
    - backendRefs:
      - name: dm-web-server
        port: 5100
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-app-server
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
  - "app-server.9m2x1z.nodes.c1.or1.k8s.ovh.us"
  - "app-server.debating.app"
  - "app-server.debates.app"
  rules:
    - backendRefs:
      - name: dm-app-server-rs
        port: 5110
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-app-server-js
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
  - "app-server-js.9m2x1z.nodes.c1.or1.k8s.ovh.us"
  - "app-server-js.debating.app"
  - "app-server-js.debates.app"
  rules:
    - backendRefs:
      - name: dm-app-server-js
        port: 5115
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-monitor
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
  - "monitor.9m2x1z.nodes.c1.or1.k8s.ovh.us"
  - "monitor.debating.app"
  - "monitor.debates.app"
  rules:
    - backendRefs:
      - name: dm-monitor-backend
        port: 5130