apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: debate-map
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-1
  postgresVersion: 13
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-1
      repoHost:
        dedicated: {}
      configuration:
      - secret:
          name: pgo-gcs-creds
      global:
        repo2-path: /db-backups-pgbackrest
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        gcs:
          bucket: "TILT_PLACEHOLDER:bucket_uniformPrivate_name"
        schedules:
          # at 3am, each Sunday (cron schedule syntax)
          full: "0 3 * * 0"
          # at 3:10am, each day (cron schedule syntax)
          differential: "10 3 * * *"
      # configuration for the next manual backup to be triggered (see deploy/pg-backups guide-module for more info)
      manual:
        repoName: repo2
        options:
         - --type=full
  patroni:
    dynamicConfiguration:
      postgresql:
        #parameters:
        #  max_parallel_workers: 2
        #  max_worker_processes: 2
        #  shared_buffers: 1GB
        #  work_mem: 2MB
        pg_hba:
          - host all all 0.0.0.0/0 md5
  users:
    - name: admin
      databases:
        - debate-map
      options: "SUPERUSER"
  metadata:
    annotations:
      # make-so the user-secret can be mirrored to the "app" namespace (see user-secret-mirror.yaml for the annotation on the "pulling" end)
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      #reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "app"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
      #reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      #reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "app"