# id
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring

# patches
spec:
  type: NodePort
  ports:
    - name: web
      port: 9090
      targetPort: web
      nodePort: 32000